CircleCI: QA automation tests

diff --git a/tests/qa/run b/tests/qa/run
--- a/tests/qa/run
+++ b/tests/qa/run
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+ROOT=$HERE/../..
 
 if [[ -z $QA_AUTOMATION_USERNAME ]]; then
 	echo "Variable QA_AUTOMATION_USERNAME is undefined." >&2
@@ -11,9 +12,33 @@ if [[ -z $QA_AUTOMATION_PASS ]]; then
 	exit 1
 fi
 
+export MODULE_VERSION=${MODULE_VERSION:-master}
+
+results() {
+	echo "$JSON" | jq "$1" | cut -d\" -f2
+}
+
 cd $HERE
-curl -f -k \
+
+json_in=$(mktemp /tmp/automation-testing.json.XXXX)
+$ROOT/deps/readies/bin/xtx -e MODULE_VERSION automation-testing.json > $json_in
+[[ $VERBOSE == 1 ]] && cat $json_in
+
+JSON=$(curl -sk \
 	-u "$QA_AUTOMATION_USERNAME":"$QA_AUTOMATION_PASS" \
 	-X POST -H "Content-Type: application/json" \
-	-d '@automation-testing.json' \
-	https://qa-automation-center.redislabs.com/processes
+	-d @$json_in \
+	https://qa-automation-center.redislabs.com/processes 2>&1)
+rc=$?
+rm $json_in
+status=$(results .status)
+if [[ $rc == 0 && $status == success ]]; then
+	id=$(results .data[0])
+	echo "Tests running."
+	echo "Results: https://qa-automation-center.redislabs.com/ui#dashboard/flow/$id"
+	exit 0
+else
+	err=$(results .message)
+	echo "Error: $err"
+	exit 1
+fi
