build redisjson module if not found in S3

diff --git a/sbin/get-redisjson b/sbin/get-redisjson
--- a/sbin/get-redisjson
+++ b/sbin/get-redisjson
@@ -151,16 +151,20 @@ WORK_DIR=$(mktemp -d /tmp/${MOD_NAME}.XXXXXX)
 if [[ -z $REPO_PATH ]]; then
 	F_MOD_RAMP="${WORK_DIR}/${MOD_RAMP}"
 	if [[ $FORCE == 1 || ! -f $F_MOD_RAMP ]]; then
-		echo "Download ${MOD_NAME} [${MOD_S3_URL}/${MOD_RAMP}] ..."
-		runn wget -P ${WORK_DIR} ${MOD_S3_URL}/${MOD_RAMP}
-		if [[ $NOP != 1 && $? != 0 ]]; then
-			if [[ BUILD == 0 ]]; then
-				eprint "Cannot download binary artifacts - build ${MOD_NAME} and set REPO_PATH"
-				exit 1
+		# check if redisjson module exists in the s3 bucket
+		if wget -q --spider ${WORK_DIR} ${MOD_S3_URL}/${MOD_RAMP}; then
+			echo "Download ${MOD_NAME} [${MOD_S3_URL}/${MOD_RAMP}] ..."
+			runn wget -P ${WORK_DIR} ${MOD_S3_URL}/${MOD_RAMP}
+		else
+			if [[ $NOP != 1 ]]; then
+				if [[ BUILD == 0 ]]; then
+					eprint "Cannot download binary artifacts - build ${MOD_NAME} and set REPO_PATH"
+					exit 1
+				fi
+				echo "Cannot download binary artifacts - building ${MOD_NAME} from source."
+				$ROOT/sbin/build-redisjson
+				exit $?
 			fi
-			echo "Cannot download binary artifacts - building ${MOD_NAME} from source."
-			$ROOT/sbin/build-redisjson
-			exit $?
 		fi
 	fi
 else
