Fix retry logic and handle bash -e

diff --git a/.github/workflows/benchmark-flow.yml b/.github/workflows/benchmark-flow.yml
--- a/.github/workflows/benchmark-flow.yml
+++ b/.github/workflows/benchmark-flow.yml
@@ -90,6 +90,8 @@ jobs:
           SEARCH_MEMORY_ENABLED: 1
         run: |
           for i in {1..3}; do
+            rc=0
+            # '|| rc=$?' prevents 'set -e' from exiting on failure, allowing retries
             redisbench-admin run-remote \
                 --module_path ../../${{ inputs.module_path }} \
                 --required-module search \
@@ -108,16 +110,17 @@ jobs:
                 --redistimeseries_host ${{ secrets.PERFORMANCE_RTS_HOST }} \
                 --redistimeseries_port ${{ secrets.PERFORMANCE_RTS_PORT }} \
                 --redistimeseries_pass '${{ secrets.PERFORMANCE_RTS_AUTH }}' \
-                --collect_search_memory True
-            if [ $? -eq 0 ]; then
+                --collect_search_memory True \
+                || rc=$?
+            if [ $rc -eq 0 ]; then
               break
             fi
             if [ $i -lt 3 ]; then
-              echo "redisbench-admin run-remote failed, attempt $i of 3, error code $?, retrying in 60 seconds..."
+              echo "redisbench-admin run-remote failed, attempt $i of 3, error code $rc, retrying in 60 seconds..."
               sleep 60
             fi
           done
-          exit $?
+          exit $rc
       - name: Generate Pull Request Performance info
         if: github.event.number
         env:
