attempt to fail san again

diff --git a/.github/workflows/common-flow-host.yml b/.github/workflows/common-flow-host.yml
--- a/.github/workflows/common-flow-host.yml
+++ b/.github/workflows/common-flow-host.yml
@@ -132,4 +132,9 @@ jobs:
       - name: Fail flow if sanitizer failed
         if: ${{ inputs.san }}
         run: |
-          [[ -n "$(ls tests/pytests/logs/*.log.* 2>/dev/null)" ]] && exit 1
+          if [[ -n "$(ls tests/pytests/logs/*.log.* 2>/dev/null)" ]]; then
+            echo "Sanitizer failed. See artifacts for logs:"
+            ls tests/pytests/logs/*.log.*
+            echo "End of sanitizer logs. Exiting with error."
+            exit 1
+          fi
