try to rerun failed

diff --git a/.github/workflows/event-merge-to-queue.yml b/.github/workflows/event-merge-to-queue.yml
--- a/.github/workflows/event-merge-to-queue.yml
+++ b/.github/workflows/event-merge-to-queue.yml
@@ -24,46 +24,56 @@ jobs:
   docs-only: # Check whether the PR is only modifying docs
     uses: ./.github/workflows/task-check-docs.yml
 
-  test-linux:
-    needs: [docs-only, get-latest-redis-tag]
-    if: needs.docs-only.outputs.only-docs-changed == 'false'
-    uses: ./.github/workflows/flow-linux-platforms.yml
-    secrets: inherit
-    with:
-      redis-ref: ${{ needs.get-latest-redis-tag.outputs.tag }}
+  # test-linux:
+  #   needs: [docs-only, get-latest-redis-tag]
+  #   if: needs.docs-only.outputs.only-docs-changed == 'false'
+  #   uses: ./.github/workflows/flow-linux-platforms.yml
+  #   secrets: inherit
+  #   with:
+  #     redis-ref: ${{ needs.get-latest-redis-tag.outputs.tag }}
 
-  test-macos:
-    needs: [docs-only, get-latest-redis-tag]
-    if: needs.docs-only.outputs.only-docs-changed == 'false'
-    strategy:
-      fail-fast: false
-      matrix:
-        mode: [standalone, coordinator]
-    uses: ./.github/workflows/flow-macos.yml
-    secrets: inherit
-    with:
-      redis-ref: ${{ needs.get-latest-redis-tag.outputs.tag }}
-      standalone:  ${{ matrix.mode == 'standalone'  }}
-      coordinator: ${{ matrix.mode == 'coordinator' }}
+  # test-macos:
+  #   needs: [docs-only, get-latest-redis-tag]
+  #   if: needs.docs-only.outputs.only-docs-changed == 'false'
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       mode: [standalone, coordinator]
+  #   uses: ./.github/workflows/flow-macos.yml
+  #   secrets: inherit
+  #   with:
+  #     redis-ref: ${{ needs.get-latest-redis-tag.outputs.tag }}
+  #     standalone:  ${{ matrix.mode == 'standalone'  }}
+  #     coordinator: ${{ matrix.mode == 'coordinator' }}
 
-  coverage:
+  # coverage:
+  #   needs: docs-only
+  #   if: needs.docs-only.outputs.only-docs-changed == 'false'
+  #   uses: ./.github/workflows/flow-coverage.yml
+  #   secrets: inherit
+
+  # sanitize:
+  #   needs: docs-only
+  #   if: needs.docs-only.outputs.only-docs-changed == 'false'
+  #   uses: ./.github/workflows/flow-sanitizer.yml
+  #   secrets: inherit
+  #   with:
+  #     flow-config: '' # full sanitization
+
+  test-that-fails:
     needs: docs-only
     if: needs.docs-only.outputs.only-docs-changed == 'false'
-    uses: ./.github/workflows/flow-coverage.yml
-    secrets: inherit
-
-  sanitize:
-    needs: docs-only
-    if: needs.docs-only.outputs.only-docs-changed == 'false'
-    uses: ./.github/workflows/flow-sanitizer.yml
-    secrets: inherit
-    with:
-      flow-config: '' # full sanitization
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail
+        run: |
+          sleep 10
+          exit 1
 
   pr-validation:
-    needs: [test-linux, test-macos, coverage, sanitize]
+    needs: [test-that-fails]
     runs-on: ubuntu-latest
     if: ${{ !cancelled() }}
     steps:
       - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
-        run: exit 1
+        run: gh run rerun ${{ github.run_id }} --failed
