MOD-9231 - Integrate Rust Benchmarks in CI (#5926)
* MOD-9231 - Integrate Rust Benchmarks in CI

Adds a github action workflow that runs the micro benchmarks (only rust for now) and provides the output as github artifact.
This workflow use two triggers (event for PR or push to integration)

1. If a PR is generated the benchmark is run and the benchmark results are stored as github artifact. If available, the benchmark is compared to a baseline from master.
2. For a push to master the benchmark is run and stored as baseline for comparison by upcoming pull requests.

Notes
- The github action only runs if files of the rust project have changed.
- The github action uses reduced setup for the benchmark environment taken from benchmark-flow.yml workflow

Remarks
- In course of the PR a leak in the C-side allocation / de-allocation shim has been fixed. see PR 5951
- For benchmark with bigger datasets, the Ubuntu github runner needs more overall time to be statistically reliable (a benchmark tool parameter, called measurement_time has been raised)
- Introduces a task to check for changes and uses this to decided if a workflow needs to run

* Less strict linker options for ubuntu in respect to symbols

Adapt the c linking for the benchmarks such that it behaves like on macos

* Raise overall time for bench to 20 seconds because of warning
You may wish to increase target time to 17.7s, enable flat sampling, or reduce sample count to 50.

* workflow tweaks, don't call rust-benchmarks but rely on `on` trigger for pushes to master

* extract memory monitoring in sh script, log the last minute memory usage to stdout

* Prepare for matrix strategy use existing event workflows

matrix strategy based on benchmark and output folder
events for pull-request and push to integration used

* fix memory monitoring

* use input memory_limit instead of magic number in workflow

* fix last minute memory usage output

* address review comments

* extract task-check-changes to use in multiple events

* wip: fix stalling of github workflows

fix condition in pr-validation
fix missing version

* concurrency runner improvements

several fixes, e.g. env variable setting for micro benchmark

* address review

diff --git a/.github/workflows/event-pull_request.yml b/.github/workflows/event-pull_request.yml
--- a/.github/workflows/event-pull_request.yml
+++ b/.github/workflows/event-pull_request.yml
@@ -11,8 +11,14 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  check-what-changed:
+    uses: ./.github/workflows/task-check-changes.yml
+    with:
+      env: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
 
   lint:
+    needs: check-what-changed
+    if: ${{ needs.check-what-changed.outputs.CODE_CHANGED == 'true' }}
     uses: ./.github/workflows/task-lint.yml
     with:
       env: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
@@ -22,6 +28,8 @@ jobs:
     uses: ./.github/workflows/task-spellcheck.yml
 
   basic-test:
+    needs: check-what-changed
+    if: ${{ needs.check-what-changed.outputs.CODE_CHANGED == 'true' }} 
     uses: ./.github/workflows/task-test.yml
     with:
       env: 'ubuntu-latest'
@@ -30,11 +38,22 @@ jobs:
       rejson-branch: master
     secrets: inherit
 
+  micro-benchmarks:
+    needs: check-what-changed
+    if: ${{ needs.check-what-changed.outputs.RUST_CODE_CHANGED == 'true' }}
+    uses: ./.github/workflows/flow-micro-benchmarks.yml
+    with:
+      env: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
+    secrets: inherit
+
   coverage:
+    needs: check-what-changed
     if: >
       (
         vars.ENABLE_CODE_COVERAGE != 'false' &&
-        (!github.event.pull_request.draft || contains(github.event.pull_request.labels.*.name, 'enforce:coverage'))
+        ((!github.event.pull_request.draft && 
+         ${{ needs.check-what-changed.outputs.CODE_CHANGED == 'true' }}
+        ) || contains(github.event.pull_request.labels.*.name, 'enforce:coverage'))
       )
     uses: ./.github/workflows/flow-coverage.yml
     with:
@@ -42,9 +61,11 @@ jobs:
     secrets: inherit
 
   sanitize:
+    needs: check-what-changed
     if: >
       (
-        (!github.event.pull_request.draft || contains(github.event.pull_request.labels.*.name, 'enforce:sanitize'))
+        ((!github.event.pull_request.draft && ${{ needs.check-what-changed.outputs.CODE_CHANGED == 'true' }}) || 
+        contains(github.event.pull_request.labels.*.name, 'enforce:sanitize')
       )
     secrets: inherit
     uses: ./.github/workflows/task-test.yml
@@ -60,11 +81,21 @@ jobs:
     needs:
       - spellcheck
       - basic-test
+      - micro-benchmarks
       - lint
       - coverage
       - sanitize
     runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
-    if: ${{ !cancelled() }}
+    if: ${{!cancelled()}}
     steps:
-      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
-        run: exit 1
+      - name: Check job results
+        run: |
+          if [[ "${{ contains(needs.*.result, 'skipped') }}" == "true" ]]; then
+            echo "One or more jobs skipped, due to change checks."
+          fi
+          
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more required jobs failed or were cancelled."
+            exit 1
+          fi
+          echo "All required jobs completed successfully or were skipped."
