wip: fix stalling of github workflows
fix condition in pr-validation
fix missing version

diff --git a/.github/workflows/event-pull_request.yml b/.github/workflows/event-pull_request.yml
--- a/.github/workflows/event-pull_request.yml
+++ b/.github/workflows/event-pull_request.yml
@@ -11,7 +11,6 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-
   lint:
     uses: ./.github/workflows/task-lint.yml
     with:
@@ -32,11 +31,14 @@ jobs:
 
   check-what-is-needed:
     uses: ./.github/workflows/task-check-changes.yml
-    
+    with:
+      env: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
+
   micro-benchmarks:
     needs: check-what-is-needed
-    if: ${{needs.check-what-is-needed.outputs.MICRO_BENCHMARK_NEEDED}}
+    if: ${{ needs.check-what-is-needed.outputs.MICRO_BENCHMARK_NEEDED == 'true' }}
     uses: ./.github/workflows/flow-micro-benchmarks.yml
+    secrets: inherit
 
   coverage:
     if: >
@@ -73,7 +75,17 @@ jobs:
       - coverage
       - sanitize
     runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
-    if: ${{ !cancelled() }}
+    if: ${{!cancelled()}}
+#    steps:
+#      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+#        run: exit 1
     steps:
-      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
-        run: exit 1
+      - name: Check job results
+        run: |
+          if [[ "${{ needs.micro-benchmarks.result }}" == "skipped" ]]; then
+            echo "Micro-benchmarks skipped (no Rust changes)."
+          elif [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more required jobs failed or were cancelled."
+            exit 1
+          fi
+          echo "All required jobs completed successfully or were skipped."
