align with master

diff --git a/.github/workflows/task-test.yml b/.github/workflows/task-test.yml
--- a/.github/workflows/task-test.yml
+++ b/.github/workflows/task-test.yml
@@ -160,6 +160,10 @@ jobs:
       - name: Enable dynamic linking to C runtime in Alpine
         if: inputs.container == 'alpine:3'
         run: echo RUST_DYN_CRT=1 >> $GITHUB_ENV
+      - name: Get Installation Mode
+        id: mode
+        run: |
+          [[ -z "${{ inputs.container }}" ]] && echo "mode=sudo" >> $GITHUB_OUTPUT || echo "mode=" >> $GITHUB_OUTPUT
       - name: Free up disk space
         run: |
           df -h
@@ -236,13 +240,33 @@ jobs:
           echo "Runner OS: $RUNNER_OS"
           echo "Runner Architecture: ${{ runner.arch }}"
           echo "========================"
-
+      - name: Setup
+        if: needs.build-image.result == 'skipped'
+        working-directory: .install
+        run: |
+          SUCCESS=0
+          for i in {1..5}; do
+            echo "Attempt $i of 5"
+            if ./install_script.sh ${{ steps.mode.outputs.mode }}; then
+              echo "Setup succeeded"
+              SUCCESS=1
+              break
+            fi
+            if [ $i -lt 5 ]; then
+              echo "Setup failed, retrying in 30 seconds..."
+              sleep 30
+            fi
+          done
+          if [ $SUCCESS -eq 0 ]; then
+            echo "Setup failed after 5 attempts"
+            exit 1
+          fi
       - name: Setup tests dependencies
         run: |
           SUCCESS=0
           for i in {1..5}; do
             echo "Attempt $i of 5"
-            if .install/test_deps/common_installations.sh; then
+            if .install/test_deps/common_installations.sh ${{ steps.mode.outputs.mode }}; then
               echo "Setup tests dependencies succeeded"
               SUCCESS=1
               break
@@ -263,7 +287,7 @@ jobs:
           SUCCESS=0
           for i in {1..5}; do
             echo "Attempt $i of 5"
-            if ./install_llvm.sh; then
+            if ./install_llvm.sh ${{ steps.mode.outputs.mode }}; then
               echo "Install LLVM for sanitizer succeeded"
               CLANG_BIN=$(find /usr/bin /usr/local/bin -name "clang-[0-9]*" 2>/dev/null | sort -V | tail -1)
               CLANG_VERSION=$(basename $CLANG_BIN | sed 's/clang-//')
@@ -306,7 +330,7 @@ jobs:
 
       - name: Build Redis
         working-directory: redis
-        run: make install
+        run:  ${{ steps.mode.outputs.mode }} make install
           BUILD_TLS=yes
           SANITIZER=${{ inputs.san }}
 
@@ -314,8 +338,7 @@ jobs:
         # Artifact names have to be unique, so we base them on the environment.
         # We also remove invalid characters from the name.
         id: artifact-names
-        run:
-          | # Invalid characters include: Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?
+        run: | # Invalid characters include: Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?
           echo "name=$(echo "${{ format('{0}', inputs.san == 'address' && 'sanitizer' || '') }} \
                              ${{ format('{0}', inputs.coverage && 'coverage test' || '') }} \
                              ${{ inputs.container || inputs.env }} ${{ runner.arch }} - Redis ${{ inputs.get-redis || 'unstable' }}" | \
