Change ref

diff --git a/.github/workflows/task-test.yml b/.github/workflows/task-test.yml
--- a/.github/workflows/task-test.yml
+++ b/.github/workflows/task-test.yml
@@ -106,7 +106,7 @@ jobs:
               # Configure the safe directory
               git config --global --add safe.directory /__w/${{ github.repository }}
 
-              # Checkout the REF
+              # Checkout
               REPO_URL="https://github.com/${{ github.repository }}.git"
 
               # Initialize a Git repository
@@ -114,8 +114,8 @@ jobs:
               git remote add origin "$REPO_URL"
 
               # Fetch and checkout ref
-              git fetch origin "$REF" || {
-                echo "Failed to fetch ref: $REF";
+              git fetch origin "${{ github.ref }}" || {
+                echo "Failed to fetch ref: '${{ github.ref }}'";
                 exit 1;
               }
               git checkout FETCH_HEAD  # Check out the fetched ref
