try

diff --git a/.github/workflows/task-test.yml b/.github/workflows/task-test.yml
--- a/.github/workflows/task-test.yml
+++ b/.github/workflows/task-test.yml
@@ -40,7 +40,7 @@ jobs:
     if: ${{ inputs.standalone || inputs.coordinator }}
     defaults:
       run:
-        shell: bash -l -eo pipefail {0}
+        shell: bash -l -eo pipefail {0} && eval $ACTIVATE_VENV
     steps:
       - name: Pre-steps Dependencies
         if: inputs.pre-steps-script
@@ -61,7 +61,8 @@ jobs:
         working-directory: setup/.install
         run: |
           ./install_script.sh ${{ steps.mode.outputs.mode }}
-          echo PATH=$PATH >> $GITHUB_ENV
+          export ACTIVATE_VENV="source venv/bin/activate"
+        #  echo PATH=$PATH >> $GITHUB_ENV
       - name: Full checkout
         uses: actions/checkout@v3
         with:
@@ -71,77 +72,79 @@ jobs:
         if: inputs.container != 'mcr.microsoft.com/cbl-mariner/base/core:2.0' && inputs.env != 'macos-12'
         run: ./sbin/setup
 
-      - name: Get Redis
-        if: inputs.get-redis != 'skip getting redis'
-        uses: actions/checkout@v3
-        with:
-          repository: redis/redis
-          ref: ${{ inputs.get-redis }}
-          path: redis
-      - name: Build Redis
-        if: inputs.get-redis != 'skip getting redis'
-        working-directory: redis
-        run: ${{ steps.mode.outputs.mode }} make install BUILD_TLS=yes
+      # - name: Get Redis
+      #   if: inputs.get-redis != 'skip getting redis'
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: redis/redis
+      #     ref: ${{ inputs.get-redis }}
+      #     path: redis
+      # - name: Build Redis
+      #   if: inputs.get-redis != 'skip getting redis'
+      #   working-directory: redis
+      #   run: ${{ steps.mode.outputs.mode }} make install BUILD_TLS=yes
 
-      - name: Decide if to continue after failure
-        id: continue-on-error
-        run: |
-          if [[ -n "${{ inputs.san }}" ]]; then
-            echo "decision=true" >> $GITHUB_OUTPUT
-          else
-            echo "decision=false" >> $GITHUB_OUTPUT
-          fi
+      # - name: Decide if to continue after failure
+      #   id: continue-on-error
+      #   run: |
+      #     if [[ -n "${{ inputs.san }}" ]]; then
+      #       echo "decision=true" >> $GITHUB_OUTPUT
+      #     else
+      #       echo "decision=false" >> $GITHUB_OUTPUT
+      #     fi
 
       - name: Build Standalone
         if: ${{ inputs.standalone }}
-        run: make SAN=${{ inputs.san }}
+        run: |
+          echo "pip path: $(which pip)"
+          make SAN=${{ inputs.san }}
       - name: Build Coordinator
         if: ${{ inputs.coordinator }}
         run: make COORD=1 SAN=${{ inputs.san }}
 
-      - name: Unit tests (standalone)
-        id: test1
-        if: ${{ inputs.standalone }}
-        continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
-        run: make unit-tests LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
-      - name: Flow tests (standalone)
-        id: test2
-        if: ${{ inputs.standalone }}
-        continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
-        run: make pytest LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }} ${{ inputs.test-config }}
-      - name: Unit tests (coordinator)
-        id: test3
-        if: ${{ inputs.coordinator }}
-        continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
-        run: make COORD=1 unit-tests LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
-      - name: Flow tests (coordinator)
-        id: test4
-        if: ${{ inputs.coordinator }}
-        continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
-        run: make COORD=1 pytest LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }} ${{ inputs.test-config }}
+      # - name: Unit tests (standalone)
+      #   id: test1
+      #   if: ${{ inputs.standalone }}
+      #   continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
+      #   run: make unit-tests LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
+      # - name: Flow tests (standalone)
+      #   id: test2
+      #   if: ${{ inputs.standalone }}
+      #   continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
+      #   run: make pytest LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }} ${{ inputs.test-config }}
+      # - name: Unit tests (coordinator)
+      #   id: test3
+      #   if: ${{ inputs.coordinator }}
+      #   continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
+      #   run: make COORD=1 unit-tests LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }}
+      # - name: Flow tests (coordinator)
+      #   id: test4
+      #   if: ${{ inputs.coordinator }}
+      #   continue-on-error: ${{ fromJson(steps.continue-on-error.outputs.decision) }}
+      #   run: make COORD=1 pytest LOG=1 CLEAR_LOGS=0 SAN=${{ inputs.san }} ${{ inputs.test-config }}
 
-      - name: Upload Artifacts
-        # skip if all tests passed
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: Test Logs
-          path: |
-            tests/logs
-            tests/pytests/logs/*.log
-          if-no-files-found: ignore
-      - name: Upload Sanitizer Artifacts
-        if: ${{ inputs.san }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: Sanitizer Logs
-          path: tests/pytests/logs/*.log.*
-          if-no-files-found: ignore
+      # - name: Upload Artifacts
+      #   # skip if all tests passed
+      #   if: failure()
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: Test Logs
+      #     path: |
+      #       tests/logs
+      #       tests/pytests/logs/*.log
+      #     if-no-files-found: ignore
+      # - name: Upload Sanitizer Artifacts
+      #   if: ${{ inputs.san }}
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: Sanitizer Logs
+      #     path: tests/pytests/logs/*.log.*
+      #     if-no-files-found: ignore
 
-      - name: Fail flow if tests failed
-        if: ${{ steps.test1.outcome == 'failure' || steps.test2.outcome == 'failure' || steps.test3.outcome == 'failure' || steps.test4.outcome == 'failure' }}
-        run: exit 1
-      - name: Fail flow if sanitizer failed
-        if: ${{ inputs.san }}
-        run: |
-          [[ -z $(ls tests/pytests/logs/*.log.* 2>/dev/null) ]] # Set exit code to 0 if no sanitizer logs were found, otherwise 1
+      # - name: Fail flow if tests failed
+      #   if: ${{ steps.test1.outcome == 'failure' || steps.test2.outcome == 'failure' || steps.test3.outcome == 'failure' || steps.test4.outcome == 'failure' }}
+      #   run: exit 1
+      # - name: Fail flow if sanitizer failed
+      #   if: ${{ inputs.san }}
+      #   run: |
+      #     [[ -z $(ls tests/pytests/logs/*.log.* 2>/dev/null) ]] # Set exit code to 0 if no sanitizer logs were found, otherwise 1
