[8.4] Get GitHub Actions working on Alpine (#7805)
* Get GitHub Actions working on Alpine (#7748)

* Install a compatibility shim to get node20 working on Alpine 3.

* Fix the container case

* Sidestep GitHub's Alpine detection.

* Fix.

* Workaround.

* Fix formatting

* Fix

* Simplify.

* Mount the expected folders.

* Last fix?

* Be defensive

* simplifications and reordering

* attempt

* attempt

* attempt

* attempt

* attempt

* test

* disable test

* rename SETUP_RETRY_LOOP

* fix sanitizer

---------

Co-authored-by: GuyAv46 <guy.avimor@gmail.com>
(cherry picked from commit 7fad39946f6c0f3096472adf241eaa19672a533a)

* [CI] Fix Alpine snapshot build (#7799)

* install bash

* make retry loop shell generic

(cherry picked from commit ff65f23bb6a6a25003b146beaae65d5fc5d58166)

---------

Co-authored-by: Luca Palmieri <20745048+LukeMathWalker@users.noreply.github.com>

diff --git a/.github/workflows/task-build-artifacts.yml b/.github/workflows/task-build-artifacts.yml
--- a/.github/workflows/task-build-artifacts.yml
+++ b/.github/workflows/task-build-artifacts.yml
@@ -47,54 +47,48 @@ jobs:
     name: Build ${{ needs.get-config.outputs.name }}
     needs: [get-config]
     runs-on: ${{ needs.get-config.outputs.env || vars.RUNS_ON || 'ubuntu-latest' }}
-    container: ${{ needs.get-config.outputs.container || null }}
     defaults:
       run:
         shell: bash -l -eo pipefail {0}
+    container: ${{
+      needs.get-config.outputs.container
+        && fromJSON(
+          format('{{"image":"{0}","options":"--user root {1}"}}',
+            needs.get-config.outputs.container,
+            needs.get-config.outputs.container == 'alpine:3.22' && '-v /opt:/opt:rw,rshared -v /opt:/__e/node20:ro,rshared' || '')
+        )
+      || null }}
+
     env:
       VERBOSE: 1 # For logging
       RELEASE: 0 # We build snapshots. This variable is used in the pack name (see `make pack`)
       # Build command
       BUILD_CMD: echo '::group::Build' && make build VERBOSE= GIT_BRANCH=$BRANCH && echo '::endgroup::'
       GITHUB_REPOSITORY: ${{ github.repository }}
+      SETUP_RETRY_LOOP: |
+        SUCCESS=0
+        for i in 1 2 3 4 5; do
+          echo "Attempt $i of 5"
+          if {0}; then
+            echo "Setup succeeded"
+            SUCCESS=1
+            break
+          fi
+          if [ $i -lt 5 ]; then
+            echo "Setup failed, retrying in 30 seconds..."
+            sleep 30
+          fi
+        done
+        [ $SUCCESS -eq 1 ] || exit 1
     steps:
       # Setup
-      # Split to alpine and non-alpine due to different default shells, once the dependency installation is done, we can use the same shell in the rest of the flow
-      - name: Setup Dependencies (Alpine)
-        if: needs.get-config.outputs.setup_script && needs.get-config.outputs.container == 'alpine:3.22'
+      - name: Install bash
+        if: needs.get-config.outputs.container == 'alpine:3.22'
         shell: sh -l -eo pipefail {0}
-        run: |
-          SUCCESS=0
-          for i in {1..5}; do
-            echo "Attempt $i of 5"
-            if ${{ needs.get-config.outputs.setup_script }}; then
-              echo "Setup Dependencies succeeded"
-              SUCCESS=1
-              break
-            fi
-            if [ $i -lt 5 ]; then
-              echo "Setup Dependencies failed, retrying in 30 seconds..."
-              sleep 30
-            fi
-          done
-          [ $SUCCESS -eq 1 ] || exit 1
-      - name: Setup Dependencies (Non-Alpine)
-        if: needs.get-config.outputs.setup_script && needs.get-config.outputs.container != 'alpine:3.22'
-        run: |
-          SUCCESS=0
-          for i in {1..5}; do
-            echo "Attempt $i of 5"
-            if ${{ needs.get-config.outputs.setup_script }}; then
-              echo "Setup Dependencies succeeded"
-              SUCCESS=1
-              break
-            fi
-            if [ $i -lt 5 ]; then
-              echo "Setup Dependencies failed, retrying in 30 seconds..."
-              sleep 30
-            fi
-          done
-          [ $SUCCESS -eq 1 ] || exit 1
+        run: ${{ format(env.SETUP_RETRY_LOOP, 'apk add bash') }}
+      - name: Setup Dependencies
+        if: needs.get-config.outputs.setup_script
+        run: ${{ format(env.SETUP_RETRY_LOOP, needs.get-config.outputs.setup_script) }}
       - name: Post-setup
         if: needs.get-config.outputs.post_setup_script
         run: ${{ needs.get-config.outputs.post_setup_script }}
@@ -108,7 +102,7 @@ jobs:
         id: node20 # TODO: Remove this when node20 is supported on all platforms, or when we drop support for these platforms
         run: |
           CONTAINER="${{ needs.get-config.outputs.container }}"
-          for platform in amazonlinux:2 alpine:3.22; do
+          for platform in amazonlinux:2; do
             if [[ "$CONTAINER" == "$platform" ]]; then
               echo "supported=false" >> $GITHUB_OUTPUT
               exit 0
@@ -128,7 +122,7 @@ jobs:
           CONTAINER="${{ needs.get-config.outputs.container }}"
           echo "Detected platform: $CONTAINER"
           case "$CONTAINER" in
-            amazonlinux:2 | alpine:3.22)
+            amazonlinux:2)
 
               # Configure the safe directory
               git config --global --add safe.directory "/__w/$GITHUB_REPOSITORY"
@@ -157,70 +151,20 @@ jobs:
           esac
       - name: Setup
         working-directory: .install
-        run: |
-          SUCCESS=0
-          for i in {1..5}; do
-            echo "Attempt $i of 5"
-            if ./install_script.sh ${{ steps.mode.outputs.mode }}; then
-              echo "Setup succeeded"
-              SUCCESS=1
-              break
-            fi
-            if [ $i -lt 5 ]; then
-              echo "Setup failed, retrying in 30 seconds..."
-              sleep 30
-            fi
-          done
-          [ $SUCCESS -eq 1 ] || exit 1
+        env:
+          INSTALL_MODE: ${{ steps.mode.outputs.mode }}
+        run: ${{ format(env.SETUP_RETRY_LOOP, './install_script.sh $INSTALL_MODE') }}
       - name: Install aws cli
         working-directory: .install
-        run: |
-          SUCCESS=0
-          for i in {1..5}; do
-            echo "Attempt $i of 5"
-            if ./install_aws.sh ${{ steps.mode.outputs.mode }}; then
-              echo "Install aws cli succeeded"
-              SUCCESS=1
-              break
-            fi
-            if [ $i -lt 5 ]; then
-              echo "Install aws cli failed, retrying in 30 seconds..."
-              sleep 30
-            fi
-          done
-          [ $SUCCESS -eq 1 ] || exit 1
+        env:
+          INSTALL_MODE: ${{ steps.mode.outputs.mode }}
+        run: ${{ format(env.SETUP_RETRY_LOOP, './install_aws.sh $INSTALL_MODE') }}
       - name: Setup test dependencies
-        run: |
-          SUCCESS=0
-          for i in {1..5}; do
-            echo "Attempt $i of 5"
-            if .install/test_deps/common_installations.sh ${{ steps.mode.outputs.mode }}; then
-              echo "Setup test dependencies succeeded"
-              SUCCESS=1
-              break
-            fi
-            if [ $i -lt 5 ]; then
-              echo "Setup test dependencies failed, retrying in 30 seconds..."
-              sleep 30
-            fi
-          done
-          [ $SUCCESS -eq 1 ] || exit 1
+        env:
+          INSTALL_MODE: ${{ steps.mode.outputs.mode }}
+        run: ${{ format(env.SETUP_RETRY_LOOP, '.install/test_deps/common_installations.sh $INSTALL_MODE') }}
       - name: install build artifacts req
-        run: |
-          SUCCESS=0
-          for i in {1..5}; do
-            echo "Attempt $i of 5"
-            if uv pip install -q -r .install/build_package_requirments.txt; then
-              echo "Install build artifacts req succeeded"
-              SUCCESS=1
-              break
-            fi
-            if [ $i -lt 5 ]; then
-              echo "Install build artifacts req failed, retrying in 30 seconds..."
-              sleep 30
-            fi
-          done
-          [ $SUCCESS -eq 1 ] || exit 1
+        run: ${{ format(env.SETUP_RETRY_LOOP, 'uv pip install -q -r .install/build_package_requirments.txt') }}
 
       # Get Redis
       - name: Get Redis (node20)
