improved workflow

diff --git a/.github/workflows/task-get-latest-tag.yml b/.github/workflows/task-get-latest-tag.yml
--- a/.github/workflows/task-get-latest-tag.yml
+++ b/.github/workflows/task-get-latest-tag.yml
@@ -15,6 +15,9 @@ on:
         description: "Latest release tag"
         value: ${{ jobs.get-tag.outputs.tag }}
 
+env:
+  RETRY_COUNT: 10
+  RETRY_MAX_TIME: 60 # seconds
 
 jobs:
   get-tag: # Following best practices: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
@@ -29,6 +32,8 @@ jobs:
         # Get the `tag_name` of the latest release (latest patch of latest minor of latest major)
         run: |
           echo "tag=$(curl -sL \
+                           --retry ${{ env.RETRY_COUNT }} \
+                           --retry-max-time ${{ env.RETRY_MAX_TIME }} \
                            -H "Accept: application/vnd.github+json" \
                            -H "X-GitHub-Api-Version: 2022-11-28" \
                            https://api.github.com/repos/${{ inputs.repo }}/releases/latest | \
@@ -40,8 +45,14 @@ jobs:
         # Get 30 latest releases (by date), filter by prefix, sort by version, get the last one
         run: |
           echo "tag=$(curl -sL \
+                           --retry ${{ env.RETRY_COUNT }} \
+                           --retry-max-time ${{ env.RETRY_MAX_TIME }} \
                            -H "Accept: application/vnd.github+json" \
                            -H "X-GitHub-Api-Version: 2022-11-28" \
                            https://api.github.com/repos/${{ inputs.repo }}/releases | \
                       jq -r '.[].tag_name | select(startswith("${{ inputs.prefix }}"))' | \
                       sort -V | tail -1)" >> $GITHUB_OUTPUT
+
+      - name: Validate Tag
+        if: ${{ steps.latest.outputs.tag == 'null' || steps.with-prefix.outputs.tag == 'null' }}
+        run: exit 1 # Fail if no tag was found
