old

diff --git a/.github/workflows/task-build-artifacts.yml b/.github/workflows/task-build-artifacts.yml
--- a/.github/workflows/task-build-artifacts.yml
+++ b/.github/workflows/task-build-artifacts.yml
@@ -28,7 +28,6 @@ on:
 env:
   REF: ${{ inputs.sha || inputs.ref || github.sha }}  # Define fallbacks for ref to checkout
   BRANCH: ${{ inputs.ref || github.ref_name }}        # Define "branch" name for pack name (used in `make pack`)
-  BOOST_VERSION: ${{ vars.BOOST_VERSION }}
   AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_UPLOAD_AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_UPLOAD_AWS_SECRET_ACCESS_KEY }}
   AWS_REGION: ${{ vars.ARTIFACT_UPLOAD_AWS_REGION }}
@@ -48,23 +47,21 @@ jobs:
       BUILD_CMD: echo '::group::Build' && make build VERBOSE= GIT_BRANCH=$BRANCH && echo '::endgroup::'
     steps:
       # Setup
-      - name: Pre-steps Dependencies
-        if: inputs.pre-steps-script
-        shell: bash -l -eo pipefail {0}
+      # Split to alpine and non-alpine due to different default shells, once the dependency installation is done, we can use the same shell in the rest of the flow
+      - name: Pre-steps Dependencies (Alpine)
+        if: inputs.pre-steps-script && inputs.container == 'alpine:3'
+        shell: sh -l -eo pipefail {0}
         run: ${{ inputs.pre-steps-script }}
       - name: Pre-steps Dependencies (Non-Alpine)
         if: inputs.pre-steps-script && inputs.container != 'alpine:3'
         run: ${{ inputs.pre-steps-script }}
-      - name: Enable dynamic linking to C runtime in Alpine
-        if: inputs.container == 'alpine:3'
-        run: echo RUST_DYN_CRT=1 >> $GITHUB_ENV
 
       - name: Get Installation Mode
         id: mode
         run: |
           [[ -z "${{ inputs.container }}" ]] && echo "mode=sudo" >> $GITHUB_OUTPUT || echo "mode=" >> $GITHUB_OUTPUT
       - name: Check if node20 is Supported
-        id: node20 # TODO: Remove this when node20 is supported on all platforms, or when we drop support for theses platforms
+        id: node20 # TODO: Remove this when node20 is supported on all platforms, or when we drop support for these platforms
         run: |
           for platform in ubuntu:bionic amazonlinux:2 alpine:3; do
             if [[ "${{ inputs.container }}" == "$platform" ]]; then
@@ -73,40 +70,19 @@ jobs:
             fi
           done
           echo "supported=true" >> $GITHUB_OUTPUT
-      - name: Deps checkout (node20)
+      - name: checkout (node20)
         if: steps.node20.outputs.supported == 'true'
         uses: actions/checkout@v4
         with:
-          path: setup
+          submodules: recursive
           ref: ${{ env.REF }}
-          sparse-checkout-cone-mode: false
-          sparse-checkout: |
-            .install
-            tests/pytests/requirements.txt
-      - name: Deps checkout (node20 not supported)
+      - name: checkout (node20 not supported)
         if: steps.node20.outputs.supported == 'false'
         run: |
           # Execute the logic based on the detected platform
           echo "Detected platform: ${{ inputs.container }}"
           case "${{ inputs.container }}" in
             ubuntu:bionic | amazonlinux:2 | alpine:3)
-              echo "Installing prerequisites for ${{ inputs.container }}..."
-
-              # Install git (platform-specific package management)
-              case "${{ inputs.container }}" in
-                ubuntu:bionic)
-                  apt update
-                  apt install -y git
-                  ;;
-                amazonlinux:2)
-                  yum update -y
-                  yum install -y git
-                  ;;
-                alpine:3)
-                  apk update
-                  apk add --no-cache git
-                  ;;
-              esac
 
               # Configure the safe directory
               git config --global --add safe.directory /__w/${{ github.repository }}
@@ -119,8 +95,8 @@ jobs:
               git remote add origin "$REPO_URL"
 
               # Fetch and checkout ref
-              git fetch origin "${{ github.ref }}" || {
-                echo "Failed to fetch ref: '${{ github.ref }}'";
+              git fetch origin "${{ env.REF }}" || {
+                echo "Failed to fetch ref: '${{ env.REF }}'";
                 exit 1;
               }
               git checkout FETCH_HEAD  # Check out the fetched ref
@@ -133,41 +109,16 @@ jobs:
               exit 1
               ;;
           esac
-      - name: Setup specific (node20)
-        if: steps.node20.outputs.supported == 'true'
-        working-directory: setup/.install
-        run: |
-          ./install_script.sh ${{ steps.mode.outputs.mode }}
-      - name: Setup specific (node20 not supported)
-        if: steps.node20.outputs.supported == 'false'
+      - name: Setup
         working-directory: .install
-        run: |
-          ./install_script.sh ${{ steps.mode.outputs.mode }}
-      - name: Install aws cli (node20)
-        if: steps.node20.outputs.supported == 'true'
-        working-directory: setup/.install
-        run: ./install_aws.sh ${{ steps.mode.outputs.mode }}
-      - name: Install aws cli (node20 not supported)
-        if: steps.node20.outputs.supported == 'false'
+        run: ./install_script.sh ${{ steps.mode.outputs.mode }}
+      - name: Install aws cli
         working-directory: .install
         run: ./install_aws.sh ${{ steps.mode.outputs.mode }}
-      - name: Full checkout (node20)
-        if: steps.node20.outputs.supported == 'true'
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
-          ref: ${{ env.REF }}
-      - name: Full checkout (node20 not supported)
-        if: steps.node20.outputs.supported == 'false'
-        run: echo "Done already earlier."
-      - name: Setup common
+      - name: Setup test dependencies
         run: .install/test_deps/common_installations.sh ${{ steps.mode.outputs.mode }}
       - name: install build artifacts req
         run: pip install -q -r .install/build_package_requirments.txt
-
-      - name: Install Boost
-        working-directory: .install
-        run: ./install_boost.sh ${{ env.BOOST_VERSION }} ${{ steps.mode.outputs.mode }}
 
       # Get Redis
       - name: Get Redis (node20)
@@ -257,6 +208,5 @@ jobs:
           aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
           aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
           aws configure set region "$AWS_REGION"
-
       - name: Upload Artifacts
         run: make upload-artifacts
