run only if inputs.container

diff --git a/.github/workflows/task-test.yml b/.github/workflows/task-test.yml
--- a/.github/workflows/task-test.yml
+++ b/.github/workflows/task-test.yml
@@ -52,6 +52,7 @@ env:
 
 jobs:
   build-image:
+    if: ${{ inputs.container }}
     name: Build container for ${{ inputs.container || inputs.env }}, Redis ${{ inputs.get-redis || 'unstable' }}
     runs-on: ${{ inputs.env }}
     permissions:
@@ -106,9 +107,9 @@ jobs:
     runs-on: ${{ inputs.env }}
     needs: build-image
     container:
-      image: ${{ needs.build-image.outputs.image }}
+      image: ${{ inputs.container && needs.build-image.outputs.image || null }}
     # Nothing to do if both are `false`, skip
-    if: ${{ inputs.standalone || inputs.coordinator }}
+    if: ${{ !cancelled() && (inputs.standalone || inputs.coordinator) }}
     defaults:
       run:
         shell: bash -l -eo pipefail {0}
@@ -173,13 +174,17 @@ jobs:
       - name: Enable dynamic linking to C runtime in Alpine
         if: inputs.container == 'alpine:3'
         run: echo RUST_DYN_CRT=1 >> $GITHUB_ENV
+      - name: Get Installation Mode
+        id: mode
+        run: |
+          [[ -z "${{ inputs.container }}" ]] && echo "mode=sudo" >> $GITHUB_OUTPUT || echo "mode=" >> $GITHUB_OUTPUT
       - name: Free up disk space
         run: |
           df -h
-          rm -rf /usr/share/dotnet || true
-          rm -rf /usr/local/lib/android || true
-          rm -rf /opt/ghc || true
-          rm -rf /opt/hostedtoolcache/CodeQL || true
+          ${{ steps.mode.outputs.mode }} rm -rf /usr/share/dotnet || true
+          ${{ steps.mode.outputs.mode }} rm -rf /usr/local/lib/android || true
+          ${{ steps.mode.outputs.mode }} rm -rf /opt/ghc || true
+          ${{ steps.mode.outputs.mode }} rm -rf /opt/hostedtoolcache/CodeQL || true
           df -h
       - name: Check if node20 is Supported
         id: node20 # TODO: Remove this when node20 is supported on all platforms, or when we drop support for these platforms
@@ -249,13 +254,33 @@ jobs:
           echo "Runner OS: $RUNNER_OS"
           echo "Runner Architecture: ${{ runner.arch }}"
           echo "========================"
-
+      - name: Setup
+        if: needs.build-image.result == 'skipped'
+        working-directory: .install
+        run: |
+          SUCCESS=0
+          for i in {1..5}; do
+            echo "Attempt $i of 5"
+            if ./install_script.sh ${{ steps.mode.outputs.mode }}; then
+              echo "Setup succeeded"
+              SUCCESS=1
+              break
+            fi
+            if [ $i -lt 5 ]; then
+              echo "Setup failed, retrying in 30 seconds..."
+              sleep 30
+            fi
+          done
+          if [ $SUCCESS -eq 0 ]; then
+            echo "Setup failed after 5 attempts"
+            exit 1
+          fi
       - name: Setup Python test dependencies
         run: |
           SUCCESS=0
           for i in {1..5}; do
             echo "Attempt $i of 5"
-            if .install/test_deps/install_python_deps.sh; then
+            if .install/test_deps/install_python_deps.sh ${{ steps.mode.outputs.mode }}; then
               echo "Setup tests dependencies succeeded"
               SUCCESS=1
               break
@@ -276,7 +301,7 @@ jobs:
           SUCCESS=0
           for i in {1..5}; do
             echo "Attempt $i of 5"
-            if ./install_llvm.sh; then
+            if ./install_llvm.sh ${{ steps.mode.outputs.mode }}; then
               echo "Install LLVM for sanitizer succeeded"
               CLANG_BIN=$(find /usr/bin /usr/local/bin -name "clang-[0-9]*" 2>/dev/null | sort -V | tail -1)
               CLANG_VERSION=$(basename $CLANG_BIN | sed 's/clang-//')
@@ -319,9 +344,12 @@ jobs:
 
       - name: Build Redis
         working-directory: redis
-        run: make install
-          BUILD_TLS=yes
-          SANITIZER=${{ inputs.san }}
+      - name: Build Redis
+        working-directory: redis
+        run: |
+          ${{ steps.mode.outputs.mode }} make install \
+            BUILD_TLS=yes \
+            SANITIZER=${{ inputs.san }}
 
       - name: Set Artifact Names
         # Artifact names have to be unique, so we base them on the environment.
